sonar.projectKey=IsisAmaya_split-expenses-app-isis
sonar.organization=isisamaya
sonar.sources=./src/backend/app
sonar.python.version=3.13
sonar.python.pylint.reportPaths=pylint-report.txt
sonar.python.flake8.reportPaths=flake8-report.txt
sonar.coverage.exclusions=**/tests/**,**/setup.py,app/__init__.py
sonar.python.coverage.reportPaths=coverage.xml
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300